from autoalias import autoalias

alias_ziwu = {\
	'ZI WU TRADING RM289 14 F': 'ZIWU TRADING',\
	'ZI WU TRADING RM289 B14': 'ZIWU TRADING',\
	'ZI YI TRADING RM289 14 F': 'ZIWU TRADING',\
	'ZIWU TRADING NO285 LO': 'ZIWU TRADING',\
	'ZIWU TRADING RM289 14 F': 'ZIWU TRADING',\
	'ZIYI TRADING': 'ZIWU TRADING'}


alias_apollo = {\
"APPOLLA CHINA": "APPOLLO CHINA",\
"APOLLO CHINA": "APPOLLO CHINA"}

alias_cvs_hava = {"CVS HAVALANDIRMA SISTEMLERI SAN": "CVS HAVALANDIRMA SISTEMLERI",\
"CVS HAVALANDIRMA SISTEMLERI SAN VE": "CVS HAVALANDIRMA SISTEMLERI"}

alias_cakrilar = {"CAKIRLAR MATBAACILIK AMB SAN VE TIC": "CAKIRLAR MATBAACILIK AMBALAJ SAN",\
"CAKIRLAR MATBAACILIK AMBALAJ SAN VE": "CAKIRLAR MATBAACILIK AMBALAJ SAN"}

alias_expeditors = {"EXPEDITORS INTERNATIONAL SWITZERLAN": "EXPEDITORS INTERNATIONAL",\
"EXPEDITORS INTERNATIONAL EI": "EXPEDITORS INTERNATIONAL"
}

alias_rest = {'VOSTOK MEDIA ECHANGE': 'VOSTOK MEDIA EXCHANGE',\
"SKN ELECTRICAL SERVICES LIMITEDACCO": "SKN ELECTRICAL SERVICES",\
"SPARKLING OIL STAR G11":"SPARKLING OIL STAR",\
"AAT HOLDING SP OO": "AAT HOLDING SP",\
"3S MADENCILIK SERAMIK INSAAT NAKLI": "3S MADENCILIK SERAMIK INSAAT",\
"ADOPEN PLASTIK VE INSAAT SAN": "ADOPEN PLASTIK VE INS SAN",
"AKPEN PLS PENC AKS STI": "AKPEN PLASTIK PEN AKS NAK SAN IC VE",\
"BAARDSE BV": "BAARDSE",\
"BORTEK BORU VE TES TEK DIS": "BORTEK BORU VE TESISAT TEKNO DIS",
"BERDAN CIVATA SOMUN MAKINA YEDEK": "BERDAN CIVATA BERDAN CIVATA SOMUN",\
"BN INTERNATIONAL": "BN INTERNATIONAL BV",\
"BURHANATIN UCAR": "BURHANATTIN UCAR",\
"CHANGXING SHENGYAN IMPORT AND EXPO": "CHANGXING SHENGYAN IMPORT EXPORT",\
"MAKTEK KAZAN RADYATOR VE KLIMA SAN": "MAKTEK KAZAN RADYATOR VE",\
"MAKSGRUP PLASTIK SAGLIK GERECLERI": "MAKSGRUP PLASTIK SAGLIK",\
"MAJOR AUTOMOTIVE GOUP": "MAJOR AUTOMOTIVE GROUP",\
"METASTAR INVEST CORNWALL BUILD": "METASTAR INVEST",\
"ZHEJIANG WEIDA INDUSTRY INVESTMEN": "ZHEJIANG WEIDA INDUSTRY AND INVESTM",\
"RIVARLANE": "RIVERLANE",\
"ARAS GLOBAL TIC VE LOJ TUR STI": "ARAS GLOBAL TICARET VE LOJISTIK",\
"DEKORPANEL ISI SISTEMLERI PAZ SAN": "DEKOR PANEL ISI SISTEMLERI PAZ",\
"GEDIK DOKUM VE VANA SANAYI": "GEDIK DOKUM VE VANA SAN",\
"JX NIPPON OIL AND ENERJY RUS": "JX NIPPON OIL AND ENERGY RUS",\
"PAKARD": "PAKART",\
"PINGCHUAN TRADE ADD RM": "PINGCHUAN TRADE",\
"PETRO CANADA EUROPE LUBRICANTS LIMI": "PETRO CANADA EUROPE LUBRICANTS",
"PJSC ARCELORMITTAL KRYVYI RIH": "PJSC ARCELORMITTAL KRYVIY RIH",
"YOTO IMPORT EXPORT": "YOTO IMPORT AND EXPORT"\
}


alias_ppl = {"ANTON SPAARGAREN BV": "ANTON SPAARGAREN"}
'''
alias = {**alias_ziwu, **alias_apollo, **alias_cakrilar, **alias_cvs_hava,\
**alias_expeditors,\
**alias_rest, **alias_ppl}
'''
alias = autoalias