autoalias = {\
"OOO DREES + SOMMER": "000 DREES SOMMER",\
"ESMIRA JAMALKHANOVA": "16006",\
"3S MADENCILIK SERAMIK INSAAT NAKLI": "3S MADENCILIK SERAMIK INSAAT",\
"AAT HOLDING SP. Z.O.O.": "AAT HOLDING SP OO",\
"AAT HOLDING SP. Z O.O.": "AAT HOLDING SP OO",\
"AGRO WEST LLC / AQRO-VEST MMM": "AGRO WEST",\
"AQRO-VEST MMM": "AGRO WEST",\
"AKPEN PLASTIK PEN.AKS.NAK.SAN.IC VE": "AKPEN PLS PENC AKS STI",\
"JAGDZIJANC ALEKSANDR": "ALEKSANDR JAGDZIJANC",\
"ALEKSANDER SPIES": "ALEXANDER SPIES",\
"ALEXANDRA GOLD KUYUMCULUK SANAYI VE": "ALEXANDRA GOLD KUYUMCULUK SANAYI",\
"ALGAN METAL SANAYI VE TICARET A.S.": "ALGAN METAL SANAYI VE TICARET ANO",\
"AL GHARABALLY NATIONAL TRADING": "ALGHARABALLY NATIONAL TRADING",\
"ULUDAG HALAT ALI ARTIS": "ALI ARTIS",\
"ARCELORMITTAL TEMIRTAU,JSC": "AO ARCELORMITTAL TEMIRTAU",\
"JSC ArcelorMittal Temirtau": "AO ARCELORMITTAL TEMIRTAU",\
"JSC ArselorMittalTemirtau": "AO ARCELORMITTAL TEMIRTAU",\
"APPOLLO (CHINA) CO., LTD": "APPOLLA CHINA",\
"APOLLO(CHINA) CO.,LTD": "APPOLLA CHINA",\
"APPOLLO(CHINA) CO.,LTD": "APPOLLA CHINA",\
"ARAS GLOBAL TIC. VE LOJ.TUR.LTD.STI": "ARAS GLOBAL TICARET VE LOJISTIK",\
"ARAS GLOBAL TICARET VE LOJISTIK TUR. LTD. STI": "ARAS GLOBAL TICARET VE LOJISTIK",\
"MARIO PALMONELLA AND ARCHITETTI": "ARCHITETTO MARIO PALMONELLA",\
"MARIO PALMONELLA": "ARCHITETTO MARIO PALMONELLA",\
"ARGON KIMYA SANAYI VE TICARET ANONI": "ARGON KIMYA SANAYI VE TICARET",\
"OJSC ARCELORMITTAL KRYVIY RIH": "ARIONA TRADING",\
"PJSC ARCELORMITTAL KRYVYI RIH": "ARIONA TRADING",\
"PJSC ARCELORMITTAL KRYVIY RIH": "ARIONA TRADING",\
"PUBLIC JOINT STOCK COMPANY ARCELOR": "ARIONA TRADING",\
"PJSC ARCELORMITTAL KRYVYI RIH,": "ARIONA TRADING",\
"ASAS ALUMINYUM SANAYI VE TICARET": "ASAS ALUMINYUM SAN VE TIC",\
"BABY DIOR - SAS ATELIERS MODELES": "ATELIERS MODELES",\
"SAS ATELIERS MODELES BABY DIOR": "ATELIERS MODELES",\
"AUTOHAUS GRAMPP GMBH": "AUTOHAUS GRAMPP MB",\
"PIERRE BALMAIN SA": "BALMAIN MAN SS 14",\
"TG - AUTOHANDELSGESELLSCHAF T MBH": "BANKVERBINDUNG TG AUTOHANDEL",\
"CAGIN MUHENDISLIK INS.OTO.SAN.TIC.": "BAROQUE POLISTREN CEPHE URUNLERI",\
"BAYRAM RZAZADE": "BAYRAM RZAYEV",\
"BILKAR SOGUTMA ISITMA KLI.VE ELEK.": "BILKAR GULER YUZLU DURUST SATICI",\
"TESLA BLATNA A.S.": "BLATNA",\
"ROMANA BOHIN S.P": "BO CONSULTING",\
"Bo.Consulting Romana Bohinc S.P.": "BO CONSULTING",\
"ROMANA BOHINC S.P.": "BO CONSULTING",\
"BURHANATTIN UCAR": "BURHANATIN UCAR",\
"CAKIRLAR MATBAACILIK AMBALAJ SAN VE": "CAKIRLAR MATBAACILIK AMBALAJ SAN",\
"CAKIRLAR MATBAACILIK AMB SAN VE TIC": "CAKIRLAR MATBAACILIK AMBALAJ SAN",\
"CELLEBRITE MOBILE SYNCHRONIZATION LTD": "CELLEBRITE MOBILE SYNCHRONIZATION L",\
"ROBERTA C.G.CAPELETTI": "CG CAPELLETTI",\
"CHANGXING SHENGYAN IMPORT AND EXPORT": "CHANGXING SHENGYAN IMPORT AND EXPO",\
"CHANGXING SHENGYAN IMPORT + EXPORT": "CHANGXING SHENGYAN IMPORT AND EXPO",\
"CHONGQING LONGFAR INDUSTRIAL CO., LTD": "CHONGQING LONGFAR INDUSTRIAL LT",\
"CHONGQING LONGFAR INDUSTRIAL CO.LTD": "CHONGQING LONGFAR INDUSTRIAL LT",\
"CHRISTIAN DIOR COUTURE": "CHRISTIAN DIOR",\
"CLAMOSA LIMITED SUITE 2 23 24 GREAT": "CLAMOSA",\
"COMMEXI FZE RAS AL KHAIMAH FREE": "COMMEXI FZE",\
"CP S.N.C. DI POMI CLAUDIO AND C": "CP SNC DI POMI CLAUDIO C",\
"CVS HAVALANDIRMA SISTEMLERI SAN. VE": "CVS HAVALANDIRMA SISTEMLERI",\
"CVS HAVALANDIRMA SISTEMLERI SAN.": "CVS HAVALANDIRMA SISTEMLERI",\
"DALGAKIRAN KOMPRESOR DIS TICARET": "DALGAKIRAN KOMPRESOR SAN VE TIC",\
"DAMIANI INTERNATIONAL BV": "DAMIANI INTERNATIO0NAL",\
"DAN ANDREI VOICU": "DAN VOICU",\
"DEKORPANEL ISI SISTEMLERI PAZ. SAN.": "DEKOR PANEL ISI SISTEMLERI PAZ",\
"DEKORPANEL ISI SISTEMLERI PAZ.SAN.": "DEKOR PANEL ISI SISTEMLERI PAZ",\
"DESJARDINS TRUST INC., IN TRUST": "DESJARDINS TRUST",\
"DEVECIOGLU METAL MADENI ESYA VE DAY": "DEVECIOGLU METAL MADENI ESYA VE",\
"DIZAYN TEKNIK BORU VE ELEMANLARI": "DIZAYN GROUP",\
"DOGUS VANA VE DOKUM SANAYI TICARET": "DOGUS VANA VE DOKUM SAN TIC",\
"DORTDIVAN CERCEVE + MACUN SAN. TIC.": "DORTDIVAN CERCEVE MACUN SAN",\
"EAST EXPERT GMBH": "EASTEXPERT",\
"EASY INTERNATIONAL LOGISTICS (HONG": "EASY INTERNATIONAL",\
"EKSEN BANT IZOLASYON VE YAPI MALZ.": "EKSEN BANT IZOLASYON VE YAPI",\
"EKSPORT TAMPL MMC": "EKSPORT TAMPL",\
"EMAKS MOBILYA AKSESUARLARI ITH. IHR": "EMAKS MOBILYA AKSESUARLARI",\
"ENSAN KALIP MAKINE SANAYI TICARET": "ENDOW",\
"ENKI IC VE DIS TIC.PAZ.DAN.SAN.TIC.": "ENKI IC VE DIS TICARET PAZ SAN TIC",\
"ERGINO ELEKTRIK VE AYDINLATMA SAN": "ERGINO ELEKTRIK VE AYDINLATMA",\
"ESKO GAYRIMENKUL VE MADENCILIK": "ESKO GAYRIMRNKUL VE MADENCILIK",\
"FACTIS S.A. S.P.A.": "FACTIS",\
"F.I.R. FABBRICA ITALIANA RADIATORI": "FARAL RADIATORI",\
"F.I.R. FABBRICA ITALIANA RADIATORI S.R.L.": "FARAL RADIATORI",\
"F.I.R.FABBRICA ITALIANA RADIATORI S": "FARAL RADIATORI",\
"DI AFFO FLAVIO +C.S.N.C": "FEDERICA COMEX",\
"FENSTER YAPI + CEPHE ELEMANLARI": "FENSTER YAPI ELEMANLARI",\
"FFDM PNEUMAT THOMAS DENTAL": "FFDM PNEUMAT",\
"FOSHAN ENSHAN IMPORT+EXPORT CO.,LTD": "FOSHAN ENSHAN IMPORT AND EXPORT",\
"GEDIK KAYNAK SANAYI VE TICARET A.S": "GEDIK DOKUM VE VANA SANAYI",\
"ONWARD LUXURY GROUP SPA": "GIBO",\
"GIMTEKS MAKINA SANAYI VE TIC A.S": "GIMTEKS MAKINA SANAYI VE TICARET",\
"GLASKUNST VOLKER KRANICH": "GLASKUNST",\
"GLOBAL GBA METAL DEKORASYON VE": "GREENGO",\
"GROHE WATER TEHNOLOGY": "GROHE",\
"TOO QTE LOQISTIK": "GTE LOGISTIK",\
"GUO YANXIA CO., LTD": "GUO YANXIA LDT",\
"GUO YANXIA CO.,LTD": "GUO YANXIA LDT",\
"HANSE TRADEING CO LIMITED": "HANSE TRADING",\
"NORDIN DENTAL": "HARALD NORDIN",\
"HDM DIS TICARET A.S.": "HDM DIS TICARET STI",\
"HDM FOREIGN TRADE INC": "HDM DIS TICARET STI",\
"HEILONGJIANG LAIKEDA IMPORT AND EXP": "HEILONGJIANG LAIKEDA IMPORT EXPORT",\
"HEILONGJIANG LAIKEDA IMPORT AND EXPORT": "HEILONGJIANG LAIKEDA IMPORT EXPORT",\
"HEMPEL (POLAND) SP.Z.O.O.": "HEMPEL PAINTS POLAND",\
"HFS INTL. LIMITED": "HFS",\
"HFS INT.LTD": "HFS",\
"HONGKONG JAFZA SANITARY WARE": "HONGKONG JAFZA SANITARY WARE INDUST",\
"HONGKONG YIXIA NG IMPORTS AND EXPORTS": "HONGKONG YIXIA NG IMPORTS",\
"HUA HE TRADE CO LIMITED RM289 14/F": "HUAHE TRADE",\
"HUAHE TRADE CO LIMIED": "HUAHE TRADE",\
"HUAHE TRADE CO LIMITED RM289 14/F G": "HUAHE TRADE",\
"HUA HE TRADE CO LIMITED": "HUAHE TRADE",\
"HUAHE TRADE CO LIMITED RM289 14/FGO": "HUAHE TRADE",\
"HUAHE TRADE CO LIMITED RM28914/F GO": "HUAHE TRADE",\
"HUA MENG TRADE CO., LTD": "HUAMENG TRADE",\
"HUAMENG TRADECO LIMITEDRM289 14/F G": "HUAMENG TRADE",\
"HUA MENG TRADE CO LIMITED": "HUAMENG TRADE",\
"HUAMENG TRADE CO LIMITED RM289 14/F": "HUAMENG TRADE",\
"IL GIOIELLO CREAZIONI SRL": "IL GIOIELLO CREAZIONI SNC",\
"IMCD TICARET PAZARLAMA VE DANISMA LTD. STI": "IMCD TIC PAZ VE DAN STI",\
"IMCD TICARET PAZARLAMA VE DANISMA": "IMCD TIC PAZ VE DAN STI",\
"INDUSTRIAS MECANICAS LAGO S.A.U.": "IML SAU",\
"IMPULSE RM INC DBA MAJOR PARTS NY": "IMPULSE RM",\
"IMPULSE RM INC DBA MAJOR PARTS": "IMPULSE RM",\
"JSC Freight One": "IN FAVOUR JSC FREIGHT ONE",\
"INKA AMBALAJ SANAYI VE INSAAT. LTD. STI.": "INKA AMBALAJ SAN VE INS STI",\
"INKA AMBALAJ SANAYI VE INSAAT.LTD.": "INKA AMBALAJ SAN VE INS STI",\
"INN5240004417.KPP524001001": "INN5240004417",\
"INN5905281886": "INN905281886",\
"EVER CHAMPION TRADING LIMITED": "INTERNATIONAL BUSINESS UNIT",\
"OOO INTERPAYP UKRAINA": "INTERPIPE UKRAINE",\
"DORU IOAN IORGULESCU": "IORGULESCU DORU IOAN",\
"ISA S.P.A. SOCIETA A SOCIO UNICO": "ISA",\
"IZOBIL YAPI KIMYASALLARI TIC.LTD": "IZOBIL YAPI KIMYASALLAR",\
"IZOBIL YAPI KIMYASALLARI TIC. LTD": "IZOBIL YAPI KIMYASALLAR",\
"IZOBIL YAPI KIMYASALLARI TIC.LTD. S": "IZOBIL YAPI KIMYASALLAR",\
"JIANGYIN ZHONGJIANG PREPAINTED STEE": "JIANGYIN ZHONGJIANG PREPAINTED",\
"JIANGYIN ZHONGJIANG PREPAINTED STEEL": "JIANGYIN ZHONGJIANG PREPAINTED",\
"ERTRANS SIA": "JUVS SIA",\
"JX NIPPON OIL AND ENERGY (RUS) LLC": "JX NIPPON OIL AND ENERJY RUS",\
"JX NIPPON OIL AND ENERGY(RUS)LLC": "JX NIPPON OIL AND ENERJY RUS",\
"KAI FANG TRADING CO., LIMITED": "KAI FANG TRADING LIMITEDRM 289B",\
"KAI YUAN TRADING CO LIMITED RM289 1": "KAI YUAN TRADING",\
"KALEKIM KIMYEVI MADDELER SANAYI VE TIC": "KALEKIM KIMYEVI MADDELER SANAYI",\
"HAMZA KARIMOV": "KARIMOV HAMZA",\
"Yuliya Kazlouskaya": "KAZLOUSKAYA YULIYA",\
"LAPLAINE MANAGEMENT LIMITED": "LAPLAINE MANAGEMENT AKARA B",\
"LCI TR KIMYA ITH. IHR. TICARET LIMI": "LCI TR KIMYA ITH IHR TICARET",\
"EXPEDITORS INTERNATIONAL E.I.": "LORO PIANA",\
"EXPEDITORS INTERNATIONAL SWITZERLAND": "LORO PIANA",\
"EXPEDITORS INTERNATIONAL SWITZERLAN": "LORO PIANA",\
"EXPEDITORS INTERNATIONAL": "LORO PIANA",\
"AVENUE LTD": "LORO PIANA",\
"CARE SURGICALS": "M RAVI KUMAR",\
"MAJOR AUTOMOTIVE GOUP INC.": "MAJOR AUTOMOTIVE GROUP",\
"MAMEDOVS COMPANY LTS": "MAMEDOVS COMPANY",\
"MARTINI GROUP": "MARTINI",\
"MEGA DANISMANLIK TEMSILCILIK DIS": "MEGA DANISMANLIK TEMSILCILIK",\
"HALLA MEISTER LTD.": "MEISTER",\
"MEKAN DUZENLEME SAN.TIC. LTD.": "MEKAN DUZENLEME SAN TIC STI",\
"METASTAR INVEST LLP CORNWALL BUILD.": "METASTAR INVEST",\
"OOO METINVEST-UKRAINE": "METINVEST UKRAINE",\
"SAMI PLASTIC SPA": "MI PLASTIC",\
"Aruna Dackeviciene": "MISS ARUNA DACKEVICIENE",\
"SPECIAL MEDIKAL SERV OF THE PR AR": "MODIAR",\
"SPECIAL STATE PROTECTION SERVICE": "MODIAR",\
"MR.MORAKIS CHRISTOS": "MORAKIS CHRISTOS",\
"DORIS MEDICAL SERVICES BERLIN": "MR ORHAN PASCHA SADE",\
"MS SONAY GULERGIN": "MS SONAY YANTAC",\
"MULTIPLAN YALITIM SISTEMLERI SAN.": "MULTIPLAN YALITIM SIS TIC",\
"Multiplan Yalitim Sistemleri San.": "MULTIPLAN YALITIM SIS TIC",\
"AKKIM KIMYA SAN VE TIC.LS": "MUSTAFA KAMIL OZKAYNAK",\
"BAYERISCHE MOTOREN WERKE AG": "NATIG MAHAMALIYEV",\
"NAZTUR SEYAHAT TICARET TURIZM LTD": "NAZTUR SEYAHAT TICARAT TURIZM",\
"NEW ZHONG YUAN CERAMICS IMPORT AND EXPORT": "NEW ZHONG YUAN CERAMICS IMPORT",\
"NEW ZHONG YUAN CERAMICS IMPORT AND": "NEW ZHONG YUAN CERAMICS IMPORT",\
"NEWMATIC INTERNATIONAL FZCO": "NEWMATIC TRADING",\
"Newmatic International FZCO": "NEWMATIC TRADING",\
"NOTA ISI VE YAPI SISTEMLERI SAN.TIC": "NOTA ISI VE YAPI SISTEMLERI SANAYI",\
"NOTA ISI VE YAPI SISTEMLERI SANAYI TIC": "NOTA ISI VE YAPI SISTEMLERI SANAYI",\
"FONDAZIONE NOVAE TERRAE": "NOVAE TERRAE",\
"JCS MAGNITOGORSK IRON AND STEEL": "OAO MMK",\
"JSC MAGNITOGORSK IRON AND STEEL / OAO MMK": "OAO MMK",\
"JCS MAGNITOGORSK IRON + STEEL WORKS": "OAO MMK",\
"JSC MAGNITOGORSK IRON AND": "OAO MMK",\
"O AND O S.R.L.": "OO",\
"LLC TRADITION FOR QUALITY": "OOO TRADICHII KACHESTVA",\
"LLC UKRDOORS": "OOO UKRDORS",\
"ORKA AHSAP URUNLERI SAN.VE TIC.LTD": "ORKA AHSAP URUNLERI SANVE TIC",\
"PAJUNK Gmbh Medizintechnologie.": "PAJUNK",\
"PARY INTERNATIONAL INC.": "PARI INTERNATIONAL",\
"PARY INTERNATIONAL": "PARI INTERNATIONAL",\
"PARK TASARIM PEYZAJ ENERJI MADENCIL": "PARK TASARIM PEYZAJ",\
"PETALS LASTIK SAN. VE TIC. A.S.": "PETLAS LASTIK SAN VE TIC",\
"PETRO-CANADA EUROPE LUBRICANTS LTD.": "PETRO CANADA EUROPE LUBRICANTS LIMI",\
"PINGCHUAN TRADE CO., LIMITED": "PINGCHUAN TRADE ADD RM",\
"PINGHENG TRADE CO LIMITED": "PINGHENG TRADE RM289 14",\
"PINGHENG TRADE CO LIMITED NO285 LOC": "PINGHENG TRADE RM289 14",\
"POLISPORTIVA DILETTANTISTICA LENTIG": "POLISPORTIVA DILETTANTISTICA",\
"POR METAL URUNLERI INSHAAT TUR. SAN": "POR METAL URUNLERI INSAAT TURIZM",\
"MARTINA BORNSCHEIN,PROMED": "PROMED",\
"MARTINA BORNSCHEIN": "PROMED",\
"PS KFZ-VERTRIEB GMBH": "PS KFZ VERTRIED",\
"OZSOY ORGANIK TEMIZLIK URN.PAZ. (PUSH CLEAN TOWELETTES)": "PUSH CLEAN TOWELETTES",\
"OZSOY ORGANIK TEMIZLIK URN.PAZ.": "PUSH CLEAN TOWELETTES",\
"BERNHARD RAAB": "RAAB BERNHARD",\
"REFLEX GORNJA RADGONA D.O.O.": "REFLEX",\
"REGULUS SYSTEM S.J.": "REGULUS SYSTEM",\
"REGULS-SYSTEM S.J.": "REGULUS SYSTEM",\
"RICHMAR LOGISTIC AND CHARTERING": "RICMAR LOGISTICS AND CHATERING",\
"RIVARLANE LLP": "RIVERLANE",\
"ROBELLO (SHANGHAI) THERMAL TECHNOLOGY": "ROBELLO THERMAL TECHNOLOGY",\
"ROBELLO (SHANGHAI) THERMAL": "ROBELLO THERMAL TECHNOLOGY",\
"ROBELLA (SHANGHAI) THERMAL TECHNOLO": "ROBELLO THERMAL TECHNOLOGY",\
"ROBELLO (SHANGHAI) THERMAL TECHNOLO": "ROBELLO THERMAL TECHNOLOGY",\
"ROBELLO(SHANGHAI)THERMAL TECHNOLOGY": "ROBELLO THERMAL TECHNOLOGY",\
"ROBERT THOMAS Metall und Elektrowerke GmbH": "ROBERT THOMAS",\
"LTD ROTACK": "ROTRACK",\
"SAFAR A SAFAROV": "SAFAR SAFAROV",\
"SAMIR RAJABOV": "SAMIR RAJADOV",\
"SAYGIN HIDROFOR VE POMPA SISTEMLERI": "SAYGIN HIDROFOR VE POMPA SIS SAN",\
"SILVEA SCHIATTI+C.SRL": "SCHIATTI C",\
"SEL DIS TICARET VE KIMYA SAN AS.": "SEL DIS TICARET VE KIMYA SANAYI",\
"SELALE DUS YAPI URUNLERI SAN.TIC.VE": "SELALE DUS YAPI URUN SAN TIC VE PAZ",\
"SENNHEISER MIDDLE EAST BRANCH": "SENNHEISER",\
"SERANIT GRANIT SERAMIK SANAYI VE": "SERANIT GRANIT SERAMIK SANAYI",\
"SERVER BOYA,MATBAA MUREKKEPLERI VE": "SERVER BOYA MATBAA MUREKKEPLERI",\
"SERVER BOYA, MATBAA MUREKKEPLERI VE": "SERVER BOYA MATBAA MUREKKEPLERI",\
"SHANGHAI QINZHITANG DISPLAY AND MAN": "SH QINZHITANG DISPLAY MANNEQUIN",\
"SHANGHAI QINZHITANG DISPLAY AND MANNEQUIN": "SH QINZHITANG DISPLAY MANNEQUIN",\
"SHUNDE LIGHT INDUSTRIAL PRODUCTS IM": "SHUNDE LIGHT INDUSTRIAL PRODUCTS",\
"SKN ELECTRICAL SERVICES LIMITEDACCO": "SKN ELECTRICAL SERVICES",\
"PJSK SLAVYANSKIE WALPAPER KFTP": "SLAVYANSKIE WALLPAPER KFTP",\
"SOGUT PLASTIK VE KALIP SANAYI VE": "SOGUT PLASTIK VE KALIP SANAYI",\
"VOROBYEV ALEXANDER": "SOLE TRADER VOROBYEV ALEXANDER",\
"SPARKLING OIL STAR LTD. G11": "SPARKLING OIL STAR",\
"SPAZIO ITALIA SRL": "SPAZIO ITALIA SRI",\
"BENETEAU SPBI SA": "SPBI",\
"STANDART IZOLASYON VE YAPI MATER": "STANDART IZOLASYON VE YAPI",\
"STILL HAIRA ACCESSORY CO LIMITED": "STILL HAIR ACCESSORY",\
"STILL HAIR ACCESSORY CO.,LTD AIL": "STILL HAIR ACCESSORY",\
"STILL HAIR ACCESSORY CO LIMTIED": "STILL HAIR ACCESSORY",\
"STORI B AND C": "STORY LORIS",\
"SWAROVSKI INTERNATIONAL DISTRIBUTION AG": "SWAROVSKI",\
"TAMSA FAYANS SERAMIK URETIM DAG.SAN": "TAMSA FAYANS SERAMIK URETIM DAGITIM",\
"TAMSA FAYANS SERAMIK URETIM DAGITIM SAN": "TAMSA FAYANS SERAMIK URETIM DAGITIM",\
"TARAS AND K KRASODARSKIY EDGE G": "TARAS AND K",\
"TASA OTOMOTIV PETROL NAKLIYAT GIDA": "TASA OTOMOTIV PETROL NAKLIYAT",\
"KAMRAN MARIF ABDULLAYEV": "TD CANADA TRUST",\
"ABDULLAYEV MARIF KAMRAN": "TD CANADA TRUST",\
"ABDULLAYEV KAMRAN": "TD CANADA TRUST",\
"KAMRAN ABDULLAYEV": "TD CANADA TRUST",\
"Tekser Akaryakıt İstasyonları Org. San. ve Tic. A.Ş.": "TEKSER AKIRYAKIT ISTASYONLARI",\
"TEMSER CELIK IMALAT,ISI,MAKINA SAN.": "TEMSER CELIK IMALAT ISI MAKINA",\
"TOO ESTVAY": "TOO ESTVAI",\
"CASTELLO DORO": "TOPROLS",\
"OOO KOMPANIYA TORGTRANSSERVIS": "TORGTRANSSERVIS",\
"FIRM TRANSRAIL UKRAINE": "TRANSRAIL UKRAINE",\
"TURSAN SERAMIK SAN VE TIC LTD STI": "TURSAN SERAMIK SAN VE TIC STL",\
"UFUK BORU": "UFUKBORU",\
"UNITED CHLORO PARAFFINS PVT.LTD": "UNITED CHLORO PARAFFINS PRIVATE",\
"UNIVAR KIMYA SAN DIS TIC.LTD.STI.": "UNIVAR",\
"UNIVAR KIMYA SANAYI VE DIS TIC LTD.": "UNIVAR KIMYA SANAYI VE DIS",\
"UNIVAR KIMYA SAN VE DIS TIC LTD.": "UNIVAR KIMYA SANAYI VE DIS",\
"VEKA KIMYA PETROL VE TAS.SAN.TIC.": "VEKA KIMYA VE PETROL",\
"VELI AKGUN INSAAT SERAMIK": "VELI AKGUN SERAMIK",\
"VELUTSAN TROSTER SYSTEME UND KOM": "VELUTSAN TROSTER SYSTEME UND",\
"VESTEL CIS LTD": "VESTEL",\
"EGE KUR.KAMU FIN.VE TIC.MRKZ.SB.": "VESTEL DIS TIC",\
"VICOVATION CORP.": "VICO VATION",\
"VITA POLYMERS POLAND SP. Z.O.O": "VITAP OLYMERSP OLANDS PZOO",\
"VITA POLYMERS POLAND SP.Z.O.O": "VITAP OLYMERSP OLANDS PZOO",\
"LKW LASIC GMBH": "VLADIMIR LASIC",\
"ZHEJIANG HUANLI ELECTRIC CO.,LTD": "WENLING HUANLI ELECTRIC",\
"ZHEJIANG HUANLI ELECTRIC CO., LTD": "WENLING HUANLI ELECTRIC",\
"XTREME MOTORCYCLE OF CAMBRIDGE": "XTREME MOTORCYCLE OUTLET",\
"YAKUT HALI TEKSTIL SANAYI VE TICARE": "YAKUT HALI TEKSTIL SAN VE TIC",\
"YALCIN SUBASI TARIM MARKET TIC. SAN. LTD STI": "YALCIN SUBASI TARIM MARKET STI",\
"YALCIN SUBASI TARIM MARKET TIC.SAN.": "YALCIN SUBASI TARIM MARKET STI",\
"BERKEL DIS TIC LTD STI": "YASEMIN CELIKEL",\
"YAZICI INSAAT VE ENDUSTRI SIHHI TESISAT": "YAZICI INSAAT VE ENDUSTRI",\
"YAZICI INSAAT VE SIHHI TESISAT": "YAZICI INSAAT VE ENDUSTRI",\
"YIWU HOLDING IMPORT AND EXPORT": "YIWU HOLDING IMPORT AND",\
"YAKAMOZ GENERAL TRADING LLC": "YOKAMOZ GENERAL TRADING",\
"YONTAR KALIP MAKINA VE INS. SAN. TIC.": "YONTAR KALIP MAK IST",\
"YONTAR KALIP MAKINA VE INS.SAN.TIC.": "YONTAR KALIP MAK IST",\
"YORK WALLCOVERINGS INC": "YORK",\
"YOTO IMPORT&EXPORT CO., LTD": "YOTO IMPORT AND EXPORT",\
"LUXURY GOODS INTERNATIONAL S.A.": "YSL SS14",\
"LUXURY GOODS INTERNATIONAL (LGI) S.A.": "YSL SS14",\
"LUXURY GOODS INTERNATIONAL S.A": "YSL SS14",\
"ZAGLIANI S.P.A. DAL 1947": "ZAGLIANI",\
"SADIYAR ZEYNALOV": "ZEYNALOV SADIYAR",\
"ZHEJIANG YIWU YING RUI FREIGHT FORWARDING": "ZHE JIANG YIWU YING RUI FREIGHT",\
"ZHEJIANG YIWU YING RUI FREIGHT FORW": "ZHE JIANG YIWU YING RUI FREIGHT",\
"THE JIANG YIWU YING RUI FREIGHT": "ZHE JIANG YIWU YING RUI FREIGHT",\
"ZHEJIANG BERKAM GARMENT CO.LTD": "ZHEJIANG BERKAM RAIMENT",\
"ZHEJIANG WEIDA INDUSTRY AND INVESTMENT": "ZHEJIANG WEIDA INDUSTRY AND INVESTM",\
"ZHEJIANG WEIDA INDUSTRY + INVESTMEN": "ZHEJIANG WEIDA INDUSTRY AND INVESTM",\
"ZHUHAI STAR WIN PIPE CO.,LTD": "ZHUHAI STARWIN PIPE",\
"ZI WU TRADING CO LIMITED RM289 14/F": "ZIWU TRADING",\
"ZI WU TRADING CO LIMITED": "ZIWU TRADING",\
"ZI WU TRADING CO LIMITED RM289 B14/": "ZIWU TRADING",\
"ZIWU TRADING CO LIMITED RM289 14/F": "ZIWU TRADING",\
"ZIWU TRADING CO LIMITED NO285 LO": "ZIWU TRADING",\
"ZI YI TRADING CO LIMITED RM289 14/F": "ZIYI TRADING",\
"ZI YI TRADING CO LIMITED": "ZIYI TRADING",\
"ZUMBOTEL LIGHTING GMBH": "ZUMTOBEL LIGHTING",\
}
